info: Connected to the database. {"timestamp":"2023-06-12T07:55:12.799Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2023-06-12T08:01:36.968Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:511:7) 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-12T08:02:02.689Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-12T08:02:06.968Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2023-06-12T08:02:44.158Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-12T08:03:14.173Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:511:7) 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-12T08:04:09.479Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:511:7) 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-12T08:05:07.423Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2023-06-12T08:05:18.842Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-12T08:05:48.856Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-12T08:07:29.396Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-12T08:07:59.410Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-12T08:10:13.592Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-12T08:10:43.592Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:511:7) 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-12T08:11:09.623Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-12T08:33:30.979Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-06-12T08:34:00.991Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-12T08:36:32.819Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:36:32.852Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:36:50.324Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:37:05.677Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:38:13.798Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:38:28.249Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:39:03.550Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:39:24.951Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:39:33.752Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:39:39.604Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:39:45.310Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:40:01.495Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:40:17.526Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-12T08:41:54.212Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:41:54.244Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:42:14.974Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-12T08:44:06.286Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:44:06.311Z"}
info: Connected to the database. {"timestamp":"2023-06-12T08:44:21.872Z"}
