info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T11:29:03.307Z"}
info: Connected to the database. {"timestamp":"2023-06-26T11:29:03.641Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T11:30:36.596Z"}
info: Connected to the database. {"timestamp":"2023-06-26T11:30:36.703Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T11:41:12.252Z"}
info: Connected to the database. {"timestamp":"2023-06-26T11:41:12.376Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T11:41:28.856Z"}
info: Connected to the database. {"timestamp":"2023-06-26T11:41:28.939Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:31:49.253Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:32:19.250Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:36:56.804Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:37:26.815Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:48:39.021Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:49:09.043Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:49:42.530Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:50:12.528Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:50:52.693Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:51:22.684Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:51:44.542Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:52:03.498Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:52:33.498Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:53:00.425Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:53:40.239Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:54:03.993Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:54:33.995Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:54:49.971Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:55:19.174Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:55:49.158Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T13:58:04.360Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (D:\\FundooApplication\\FundooApp\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:12:20)\n    at tryCatch (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at apply (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12)\n    at database (D:\\FundooApplication\\FundooApp\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\src\\/index.js:37:9)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Module._compile (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Object.newLoader [as .js] (D:\\FundooApplication\\FundooApp\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (D:\\FundooApplication\\FundooApp\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1275:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)\n    at Module.load (node:internal/modules/cjs/loader:1133:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:972:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-06-26T13:58:34.367Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:511:7) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-26T13:59:31.929Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:30:50.890Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:30:50.936Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '2', createdBy: '6495b5f83195572908f84a4d' }" (type Object) at path "_id" for model "Notes"
    at model.Query.exec (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/2 
    method - GET 
    IP - ::1
   {"timestamp":"2023-06-26T14:33:19.784Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:33:49.612Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:33:49.648Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:33:58.061Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:33:58.113Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '2', createdBy: '6495b5f83195572908f84a4d' }" (type Object) at path "_id" for model "Notes"
    at model.Query.exec (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/2 
    method - GET 
    IP - ::1
   {"timestamp":"2023-06-26T14:34:01.898Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '2', createdBy: '6495b5f83195572908f84a4d' }" (type Object) at path "_id" for model "Notes"
    at model.Query.exec (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/2 
    method - GET 
    IP - ::1
   {"timestamp":"2023-06-26T14:34:03.475Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:34:47.822Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:34:47.870Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:35:20.174Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:35:20.226Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:50:33.492Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:50:33.551Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:50:56.883Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:50:56.985Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '2', createdBy: '6495b5f83195572908f84a4d' }" (type Object) at path "_id" for model "Notes"
    at model.Query.exec (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/2 
    method - GET 
    IP - ::1
   {"timestamp":"2023-06-26T14:51:01.820Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:53:20.381Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:53:20.429Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:53:31.054Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:53:31.091Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: '2', createdBy: '6495b5f83195572908f84a4d' }" (type Object) at path "_id" for model "Notes"
    at model.Query.exec (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/2 
    method - GET 
    IP - ::1
   {"timestamp":"2023-06-26T14:53:35.412Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:56:05.955Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:56:06.021Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:56:46.495Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:56:46.536Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: 'limit=2', createdBy: '6495b5f83195572908f84a4d' }" (type Object) at path "_id" for model "Notes"
    at model.Query.exec (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\FundooApplication\FundooApp\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/limit=2 
    method - GET 
    IP - ::1
   {"timestamp":"2023-06-26T14:57:26.748Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:58:34.220Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:58:34.262Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T14:59:49.184Z"}
info: Connected to the database. {"timestamp":"2023-06-26T14:59:49.239Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:01:31.692Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:01:31.746Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:01:48.047Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:01:48.105Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:02:59.754Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:02:59.789Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:04:25.632Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:04:25.681Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:06:57.779Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:06:57.835Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:10:24.831Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:10:24.890Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:11:33.160Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:11:33.211Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:12:35.665Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:12:35.717Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:13:35.251Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:13:35.308Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:13:54.925Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:13:54.982Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:14:32.216Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:14:32.287Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:15:39.033Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:15:39.079Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:16:04.084Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:16:04.152Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:16:19.466Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:16:19.521Z"}
info: Server started at http://localhost:4001/api/v1/ {"timestamp":"2023-06-26T15:27:54.651Z"}
info: Connected to the database. {"timestamp":"2023-06-26T15:27:54.697Z"}
